# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

total = 2
current = 3
nm1 = 2
nm2 = 1

while current < 4000000 do
  total += current if current.even?
  nm2 = nm1
  nm1 = current
  current = nm1 + nm2
end

puts  "Sum of all even fib less than 4m is #{total}"